version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.15
    - 13.0.16
    - 13.0.3
    - 13.0.7
    - 13.0.9
    - 13.1.1
    - 13.1.2
    - 13.1.5
  - dependency-name: react-markdown
    versions:
    - 6.0.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
